# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: test-and-build-api

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
          cache-dependency-path: |
            ./eventapp-api/go.sum
            ./eventapp-api/go.mod

      - name: Run staticcheck
        working-directory: ./eventapp-api
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: Run vet
        working-directory: ./eventapp-api
        run: go vet -v ./...

      - name: Run govulncheck
        working-directory: ./eventapp-api
        run: |
          go version
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: Run tests
        working-directory: ./eventapp-api
        run: go test -v ./...

      - name: Build
        working-directory: ./eventapp-api
        run: go build -v ./...
